#!/usr/bin/env zsh
DOTFILES="/home/omerfaruk/.dotfiles"
STOW_FOLDERS=(i3 polybar)
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Removing $folder"
    stow -D $folder
done
popd